### ISSUE TITLE
Page and Users overview Accordion not working well...

### ISSUE THREAD

**Issue by NaimaGhulamMuhammad** [NaimaGhulamMuhammad/website-admin-dashboard#1]
![image](https://user-images.githubusercontent.com/63257312/137251139-6cf9dc15-9e63-4f7f-ac33-0076ad8046f7.png)
bootstrap Accordion needs to be fixed as you can see, In a dashboard.js file you can fix it

**Comment by sugato1398** [comment]
hi, im interested to work on it, can you please explain what is exactly the issue and how you want the display to look like?

**Comment by NaimaGhulamMuhammad** [comment]
@sugato1398  as you can see it is not aligned and does not looking like that its a toggle, so if you add an icon to show somehow...
You can check this [LIVE VIEW](https://website-admin-dashboard.netlify.app/) for further view

Go ahead
